### ISSUE TITLE
Error using GLVideo in Eclipse (osx):  no glvideo in java.library.path

### ISSUE THREAD

**Issue by filippoguida** [gohai/processing-glvideo#34]
I'm using the Processing core-library on Eclipse (JDK 8), imported following this tutorial:
[https://processing.org/tutorials/eclipse/](url)

Then, i downloaded from this Git the library and imported the following classes, collecting them into _**gohai.glvideo**_ package:

_GLCapture.java
GLMovie.java
GLVideo.java
PerspectiveTransform.java
WarpPerspective.java_

But i still have this issue trying to import a .mp4 video:
```
java.lang.UnsatisfiedLinkError: no glvideo in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at gohai.glvideo.GLVideo.loadGStreamer(GLVideo.java:109)
	at gohai.glvideo.GLVideo.<init>(GLVideo.java:66)
	at gohai.glvideo.GLMovie.<init>(GLMovie.java:36)
	at gohai.glvideo.GLMovie.<init>(GLMovie.java:57)
	at UsingProcessing.lambda$4(UsingProcessing.java:38)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at UsingProcessing.lambda$1(UsingProcessing.java:35)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at UsingProcessing.settings(UsingProcessing.java:29)
	at processing.core.PApplet.handleSettings(PApplet.java:973)
	at processing.core.PApplet.runSketch(PApplet.java:10739)
	at processing.core.PApplet.main(PApplet.java:10501)
	at processing.core.PApplet.main(PApplet.java:10483)
	at UsingProcessing.main(UsingProcessing.java:19)
```

**Comment by gohai** [comment]
@filippoguida You need to have the native library (e.g. `libglvideo.jnilib`) in your `java.library.path`. This is done automatically by Processing proper - if you're using Eclipse you need to take care of this yourself.
